# TEMPLATE FOR A DEFAULT GIG RUNNER
FROM registry.access.redhat.com/ubi9/python-312-minimal:latest
USER root

ARG OC_TAR_GZ_FILE=openshift-client-linux.tar.gz
ARG OC_CLI_URL=https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/latest/${OC_TAR_GZ_FILE}

RUN <<EOF
    set -ex
    microdnf install --assumeyes --nodocs jq go nodejs tar gzip procps-ng
    microdnf clean all
    curl -fsSLo /tmp/${OC_TAR_GZ_FILE} ${OC_CLI_URL}
    tar -C /usr/local/bin/ -xf /tmp/${OC_TAR_GZ_FILE} 'oc' 'kubectl'
    rm /tmp/${OC_TAR_GZ_FILE}
    python -m pip install jinja2 pyyaml
EOF

ENV HOME=/workDir

WORKDIR /workDir

USER 1001