FROM registry.access.redhat.com/ubi10/python-312-minimal
USER root

ARG OC_TAR_GZ_FILE=openshift-client-linux.tar.gz
ARG OC_CLI_URL=https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/latest/${OC_TAR_GZ_FILE}

COPY requirements.txt src/operator /ahplos-gigs-controller/

WORKDIR /ahplos-gigs-controller

RUN <<EOF
    set -ex
    #### ADJUST FOLLOWING FOR OTHER BASE IMAGE DISTROS ####
    microdnf install --assumeyes --nodocs tar gzip
    microdnf clean all
    #### END ADJUST FOLLOWING FOR OTHER DISTROS ####

    curl -sS https://webinstall.dev/shfmt | bash

    python --version
    python -m ensurepip --upgrade
    python -m pip install -r requirements.txt
    curl -fsSLo /tmp/${OC_TAR_GZ_FILE} ${OC_CLI_URL}
    tar -C /usr/local/bin/ -xf /tmp/${OC_TAR_GZ_FILE} 'oc' 'kubectl'
    rm /tmp/${OC_TAR_GZ_FILE}
    chmod -R 0755 /ahplos-gigs-controller
EOF

USER 1001