FROM registry.access.redhat.com/ubi9/python-312:latest
USER root

ARG OKD_VERSION=4
ARG OC_CLI_URL=https://mirror.openshift.com/pub/openshift-v${OKD_VERSION}/clients/oc/latest/linux/oc.tar.gz

COPY requirements.txt src/operator /teknetes-gigs-controller/

RUN <<EOF
    set -ex
    python --version
    python -m ensurepip
    python -m pip install --upgrade pip
    python -m pip install -r /teknetes-gigs-controller/requirements.txt
    curl -fsSLo /tmp/oc.tar.gz ${OC_CLI_URL}
    tar -C /usr/local/bin/ -xf /tmp/oc.tar.gz  'oc' 'kubectl'
    dnf clean all
    rm /tmp/oc.tar.gz
    chmod -R 0755 /teknetes-gigs-controller
EOF

USER 1001