FROM registry.access.redhat.com/ubi9/python-312:latest
USER root

ARG OC_TAR_GZ_FILE=openshift-client-linux.tar.gz
ARG OC_CLI_URL=https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/latest/${OC_TAR_GZ_FILE}

COPY requirements.txt /teknetes-gigs-controller/

WORKDIR /teknetes-gigs-controller

RUN <<EOF
    set -ex
    python --version
    python -m ensurepip
    python -m pip install --upgrade pip
    python -m pip install -r requirements.txt
    curl -fsSLo /tmp/${OC_TAR_GZ_FILE} ${OC_CLI_URL}
    tar -C /usr/local/bin/ -xf /tmp/${OC_TAR_GZ_FILE} 'oc' 'kubectl'
    rm /tmp/${OC_TAR_GZ_FILE}
    chmod -R 0755 /teknetes-gigs-controller
EOF

USER 1001