elCicdDefs:
  GIG: gig
  GIG_DEF: $<GIG>definition
  GIG_RUN: $<GIG>run
  GIG_TYPES: [$<GIG_DEF>, $<GIG>, $<GIG_RUN>]

  SCOPE: Namespaced

  FORM_SPEC:
    type: array
    description: Optional list of groups of components organized into sections of a form users will use to launch a job.
    required:
    - components
    items:
      type: object
      properties:
        attributes:
          description: |-
            A map of key/value pairs that optionally configure the form group.
          type: object
          additionalProperties:
            type: string
        var:
          description: |-
            Variable that will be assigned from the values of components in the group. Can be overriden at
            the component level.
          type: string
          pattern: '^\w+$'
        components:
          type: array
          minItems: 1
          items:
            type: object
            description: |-
              arbitrary keys corresponding to JSX PatternFly Form (e.g. TextInput or Radio) controls that contain a map of zero or more
              attributes for the control; e.g.
                - component: Radio
                  attributes:
                    label: Option 1
            properties:
              inputType:
                type: string
                enum:
                - TextArea
                - TextInput
                - Radio
                - Checkbox
              attributes:
                description: |-
                  attributes is a map of {key,value} pairs that optionally contain attributes and values for the component
                type: object
                additionalProperties:
                  type: string
            required:
            - inputType

  GIG_RUN_STATUS:
    type: object
    properties:
      creationTimestamp:
        type: string
      result:
        type: string
        enum:
        - Success
        - Failure
        - Pending
        default: Pending
      runTime:
        type: integer
      startedBy:
        type: string
      state:
        type: string
        enum:
        - WaitingForUserInput
        - Running
        - Completed
        default: Running

elCicdDefs-$<GIG_DEF>:
  TITLE_CASE_NAME: GigDefinition
  SHORT_NAMES:
  - gigdef
  - gigdefs
  SCOPE: Cluster
  SPEC_DEFINITION:
    description: $<TITLE_CASE_NAME>Spec defines a GigDefinition, and the optional and/or required parameters to launch it.
    type: object
    properties:
      name:
        type: string
      description:
        type: string
      stages:
        description: A unit of work.  User input may potentially be required at the end of a stage.
        type: array
        items:
          type: object
          properties:
            command:
              type: string
              descriptions: |
                By default, stage scripts are bash scripts and all stages will be run inside a single shell file.  If the
                script is run in an alternative language, define the command to run the script here, and use the notation
                '{}` to define where the filename should be referenced in the command. If your command need to use squiggly
                brackets, double them up; e.g. "${FOO}" would be "${{FOO}}" in the command.
            displayName:
              type: string
              description: Human readable title of stage
            description:
              type: string
              description: Description of stage
            name:
              type: string
              description: |
                Name of stage. Must start and end with an alphanumeric character, and '-' and '.' may be used.
                If a command is defined, will be used to generate a filename for the script, so name appropiately;
                e.g. <some-name>.py if running a Python script.
              pattern: '(?:^\w(?:[-\w.]{0,251}[\w])?)$'
            secrets:
              type: array
              items:
                type: object
                properties:
                  secretRef:
                    type: object
                    properties:
                      name:
                        type: string
                      keys:
                        type: array
                        items:
                          type: string
            script:
              type: string
            waitForUserInput:
              type: boolean
          required:
          - name
          - script
      formSpec: $<FORM_SPEC>

elCicdDefs-$<GIG>:
  TITLE_CASE_NAME: Gig
  SPEC_DEFINITION:
    description: $<TITLE_CASE_NAME>Spec defines the relationship between a $<GIG_DEF> and specific CronJob (i.e. JobTemplate).
    type: object
    properties:
      cronJobRef:
        description: Reference to a CronJob in the same Namespace as the Gig.
        type: object
        properties:
          name:
            description: Name of a CronJob in the same Namespace as the Gig.
            type: string
        required:
        - name
      gigDefinitionRef:
        description: Reference to a GigDefinition.
        type: object
        properties:
          name:
            type: string
        required:
        - name
  STATUS_DEFINITION:
    type: object
    properties:
      latestGigRun: $<GIG_RUN_STATUS>

elCicdDefs-$<GIG_RUN>:
  TITLE_CASE_NAME: GigRun
  SPEC_DEFINITION:
    description: $<TITLE_CASE_NAME>Spec defines a specific Job run produced from a GigBinding.
    type: object
    properties:
      gigRef:
        type: object
        properties:
          name:
            type: string
      formSpec: $<FORM_SPEC>
  STATUS_DEFINITION: $<GIG_RUN_STATUS>

elCicdTemplates:
- apiVersion: apiextensions.k8s.io/v1
  kind: CustomResourceDefinition
  objNames: $<GIG_TYPES>
  objName: $<>s.batch.teknetes.org
  template:
    spec:
      conversion:
        strategy: None
      # group name to use for REST API: /apis/<group>/<version>
      group: batch.teknetes.org
      # list of versions supported by this CustomResourceDefinition
      names:
        kind: $<TITLE_CASE_NAME>
        plural: $<BASE_OBJ_NAME>s
        singular: $<BASE_OBJ_NAME>
        shortNames: $<SHORT_NAMES>
      scope: $<SCOPE>
      preserveUnknownFields: false
      versions:
      - name: v1beta1
        served: true
        storage: true
        subresources:
          status: {}
        schema:
          openAPIV3Schema:
            description: |-
              A Gig represents an impromptu Job with arbitrary scripts, and implies user input is required, potentially in mutliple stages.
            type: object
            properties:
              apiVersion:
                description: |-
                  APIVersion defines the versioned schema of this representation of an object.
                  Servers should convert recognized schemas to the latest internal value, and
                  may reject unrecognized values.
                  More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
                type: string
              kind:
                description: |-
                  Kind is a string value representing the REST resource this object represents.
                  Servers may infer this from the endpoint the client submits requests to.
                  Cannot be updated.
                  In CamelCase.
                  More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
                type: string
              metadata:
                type: object
              spec: $<SPEC_DEFINITION>
              status: $<STATUS_DEFINITION>