elCicdDefs:
  GIG: gig
  GIG_LAUNCHFORM: $<GIG>launchform
  GIG_DEF: $<GIG>definition
  GIG_RUN: $<GIG>run
  GIG_TYPES: [$<GIG_DEF>, $<GIG_LAUNCHFORM>, $<GIG>, $<GIG_RUN>]

  RUN_STATE:
    type: string
    enum:
    - Aborted
    - Aborting
    - Failed
    - InputReceived
    - Running
    - Succeeded
    - WaitingForInput

  NAME_NAMESPACE_PROPS:
    name:
      type: string
    namespace:
      type: string

  FORM_SPEC:
    type: array
    description: |
      Optional list of groups of components organized into sections of a form users will use to launch a job.
    x-kubernetes-list-type: map
    x-kubernetes-list-map-keys:
    - var
    items:
      type: object
      required:
      - components
      - var
      properties:
        attributes:
          description: |-
            A map of key/value pairs that optionally configure a group of components.
          type: object
          additionalProperties:
            type: string
        components:
          type: array
          items:
            type: object
            description: |-
              Arbitrary keys corresponding to JSX PatternFly Form (e.g. TextInput or Radio) controls that contain a map of zero or more
              attributes for the control; e.g.
                - component: Radio
                  attributes:
                    label: Option 1
            properties:
              booleans:
                type: array
                description: |-
                  String only attributes for configuring a component; isVisible (vs isVisible="true").
                items:
                  type: string
                x-kubernetes-list-type: set
              inputType:
                type: string
                enum:
                - Checkbox
                - Dropdown
                - NumberInput
                - Radio
                - TextArea
                - TextInput
              attributes:
                type: object
                description: |-
                  Attributes are a map of {key,value} pairs for configuring a component.
                additionalProperties:
                  type: string
              tooltip:
                type: string
                description: |-
                  Tooltip for the component.
            required:
            - inputType
        var:
          description: |-
            Variable that will be assigned from the value of component(s) in the group.
          type: string
          pattern: '^\w+$'

elCicdDefs-$<GIG_LAUNCHFORM>:
  TITLE_CASE_NAME: GigLaunchForm
  SHORT_NAMES:
  - glf
  - glfs
  - gigform
  - gigforms
  SPEC_DEFINITION:
    type: object
    description: |
      $<TITLE_CASE_NAME>Spec defines a GigLaunchForm, and the optional and/or required inputValues to launch it.
    required:
    - inputForm
    properties:
      title:
        type: string
      inputForm: $<FORM_SPEC>

elCicdDefs-$<GIG_DEF>:
  TITLE_CASE_NAME: GigDefinition
  SHORT_NAMES:
  - gigdef
  - gigdefs
  SPEC_DEFINITION:
    type: object
    description: |
      $<TITLE_CASE_NAME>Spec defines a GigDefinition, and the optional and/or required inputValues to launch it.
    required:
    - name
    - activeDeadlineSeconds
    - stages
    - workDirSizeLimit
    properties:
      activeDeadlineSeconds:
        type: integer
        description: |
          Time in seconds before a GigRun will be terminated. This value will override any value set in an associated CronJob.
        default: 3600
      description:
        type: string
      gigLaunchFormRef:
        type: object
        description: |
          Optional default GigLaunchForm to use with GigDefinition. Can be overridden in a Gig.
        properties: $<NAME_NAMESPACE_PROPS>
        required:
        - name
      inputParams:
        type: array
        description: |
          List of input params used by the definition.  This list has no functional value and is not verified. Use it for
          documentation purposes only.
        items:
          type: string
        x-kubernetes-list-type: set
      name:
        type: string
      requiredInputParams:
        type: array
        description: |
          List of required input parameters that are required to launch to definition.  A Secret with the same name as the GigRun
          will be checked for existence and that the required params are defined before launching.
        items:
          type: string
        x-kubernetes-list-type: set
      secretEnvVars:
        type: array
        description: |
          List of environment variables that are secrets and should be obfuscated in GigRun logs.
        items:
          type: string
        x-kubernetes-list-type: set
      secrets:
        type: array
        description: |
          List of Secrets that will be included in a GigRun and whose values should be obfuscated in GigRun logs.  A GigRun will fail
          to start if the Secret does not exist unless it's marked optional.  Referencing a Secret here will NOT mount the Secret
          in a Pod.  It is the CronJob's/developer's responsibility to import the values.
        x-kubernetes-list-type: map
        x-kubernetes-list-map-keys:
        - name
        items:
          type: object
          required:
          - name
          properties:
            name:
              type: string
              description: |
                Name of a Kubernetes Secret that is expected to exist in a the same namespace as a GigRun.
            optional:
              type: boolean
              description: If true, ignore if the Secret is missing.
      stages:
        description: Units of work.  User input may potentially be required at the end of a name.
        type: array
        x-kubernetes-list-type: map
        x-kubernetes-list-map-keys:
        - name
        items:
          type: object
          oneOf:
          - required:
            - gigDefinitionRef
          - required:
            - script
          required:
          - name
          properties:
            command:
              type: string
              descriptions: |
                Express a custom command to run this name's source. The command should have the form
                <command> <args...> %s <args...>. %s will be used by Teknetes Gigs to inject the
                filename (i.e. the name of the name) where the source will be stored. Leave blank
                if the source is a shell source, in which case the source will be executed directly.
            description:
              type: string
              description: Description of name's purpose.
            displayName:
              type: string
              description: Human readable title of name for logging purposes.
            gigDefinitionRef:
              type: object
              properties:
                name:
                  type: string
              required:
              - name
            iterate:
              type: array
              items:
                type: object
                properties:
                  envVar:
                    type: string
                  range:
                    type: object
                    properties:
                      start:
                        type: integer
                        default: 0
                      stop:
                        type: integer
                      step:
                        type: integer
                        default: 1
                    required:
                    - stop
                  values:
                    type: array
                    items:
                      x-kubernetes-int-or-string: true
                    minLength: 1
                anyOne:
                - required:
                  - envVar
                - required:
                  - range
                - required:
                  - values
            name:
              type: string
              description: |
                Name of the stage. Must start and end with an alphanumeric character, and '-' and '.' may be used.
                The name will reflect the name of the file used to store the source, so name appropiately;
                e.g. <some-name>.py if the name is a Python source.
              pattern: '(?:^\w(?:[-\w.]{0,251}[\w])?)$'
            parallel:
              type: boolean
            scriptType:
              type: string
              description: |
                The interpretor for the stage, either a definition type or language. For 'shell', scripts are executed directly.
                For all other interpretors, scripts are mounted as files in the Pod and executed; i.e. in a subprocess. If not defined,
                then 'shell' is assumed.
              enum:
              - custom
              - gigdefinition
              - go
              - input
              - jinja-template
              - python
              - shell
              default: shell
            script:
              type: string
              description: |
                The source to execute. Can be writting in any language or definition type supported by Teknetes Gigs,
                or as a source for a custom command to run.  Can alse refer to another GigDefinition.
            secretEnvVars:
              type: array
              description: |
                A list of environment variables that should be obfuscated in the logs. Because these variables may
                be assigned before the log filtering component is aware of the variable, debug logging/tracing will be turned
                off for this stage if secretEnvVars are defined.  Once declared, the value assigned in this stage
                will be obfuscated throughout the GigRun. If the value needs to be updated in a subsequent stage,
                it will need to be redeclared.
              items:
                type: string
              x-kubernetes-list-type: set
            wait:
              type: boolean
            when:
              type: string
              description: |
                Javascript statement that must evaluate to `true` for the name to execute. For ease of writing expressions,
                environment variables are copied into the `env` Javascript object; e.g. FOO='some value' in shell can be refered
                to as `env.FOO` in the statements.
            workDir:
              type: string
      workDirSizeLimit:
        pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
        x-kubernetes-int-or-string: true
        default: 10Mi

elCicdDefs-$<GIG>:
  TITLE_CASE_NAME: Gig
  SPEC_DEFINITION:
    description: $<TITLE_CASE_NAME>Spec defines the relationship between a $<GIG_DEF> and specific CronJob (i.e. JobTemplate).
    type: object
    properties:
      cronJobRef:
        description: Reference to a CronJob in the same Namespace as the Gig.
        type: object
        properties:
          name:
            description: Name of a CronJob in the same Namespace as the Gig.
            type: string
        required:
        - name
      gigDefinitionRef:
        description: Reference to a GigDefinition.
        type: object
        properties: $<NAME_NAMESPACE_PROPS>
        required:
        - name
      gigLaunchFormRef:
        description: Reference to a GigLaunchForm.
        type: object
        properties: $<NAME_NAMESPACE_PROPS>
        required:
        - name
    required:
    - cronJobRef
    - gigDefinitionRef
  STATUS_DEFINITION:
    type: object
    properties:
      latestGigRun:
        type: object
        properties:
          creationTimestamp:
            type: string
          name:
            type: string
          runState: $<RUN_STATE>
          runTime:
            type: integer
          startedBy:
            type: string

elCicdDefs-$<GIG_RUN>:
  TITLE_CASE_NAME: GigRun
  SPEC_DEFINITION:
    type: object
    description: |
      $<TITLE_CASE_NAME>Spec defines a specific Job run produced from the parent Gig's CronJob.
    properties:
      gigRef:
        type: object
        properties:
          name:
            type: string
            x-kubernetes-validations:
            - rule: "!(self != oldSelf)"
              message: gigRef name and containerName are immutable
          containerName:
            type: string
            x-kubernetes-validations:
            - rule: "!(self != oldSelf)"
              message: gigRef name and containerName are immutable
        required:
        - name
      inputForm: $<FORM_SPEC>
      inputReceived:
        type: boolean
        default: false
      inputValues:
        type: object
        description: |
          Dictionary of input values to pass to a Pod when starting a GigRun, or to resume execution when paused for further input.
          InputValues are never preserved in a deployed GigRun, but rather used by the Gig Operator to create an associated Secret for
          the Pod to read and use.
        x-kubernetes-preserve-unknown-fields: true
        properties:
          additionalProperties:
            type: string
      startedBy:
        type: string
        x-kubernetes-validations:
        - rule: "size(oldSelf) > 0 && !(self != oldSelf)"
          message: startedBy is immutable
    required:
    - gigRef
  STATUS_DEFINITION:
    type: object
    properties:
      runState: $<RUN_STATE>
      runTime:
        type: integer

elCicdTemplates:
- apiVersion: apiextensions.k8s.io/v1
  kind: CustomResourceDefinition
  objNames: $<GIG_TYPES>
  objName: $<>s.batch.teknetes.org
  template:
    spec:
      conversion:
        strategy: None
      # group name to use for REST API: /apis/<group>/<version>
      group: batch.teknetes.org
      # list of versions supported by this CustomResourceDefinition
      names:
        kind: $<TITLE_CASE_NAME>
        plural: $<BASE_OBJ_NAME>s
        singular: $<BASE_OBJ_NAME>
        shortNames: $<SHORT_NAMES>
      scope: Namespaced
      preserveUnknownFields: false
      versions:
      - name: v1beta1
        served: true
        storage: true
        subresources:
          status: {}
        schema:
          openAPIV3Schema:
            type: object
            properties:
              apiVersion:
                description: |-
                  APIVersion defines the versioned definition of this representation of an object.
                  Servers should convert recognized schemas to the latest internal value, and
                  may reject unrecognized values.
                  More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
                type: string
              kind:
                description: |-
                  Kind is a string value representing the REST resource this object represents.
                  Servers may infer this from the endpoint the client submits requests to.
                  Cannot be updated.
                  In CamelCase.
                  More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
                type: string
              metadata:
                type: object
              spec: $<SPEC_DEFINITION>
              status: $<STATUS_DEFINITION>