elCicdDefs:
  GIG: gig
  GIG_DEF: $<GIG>definition
  GIG_RUN: $<GIG>run
  GIG_TYPES: [$<GIG_DEF>, $<GIG>, $<GIG_RUN>]

  SCOPE: Namespaced

  FORM_SPEC:
    type: object
    properties:
      inputvalues: $<INPUT_VALUES>
      spec:
        type: array
        description: Optional list of groups of components organized into sections of a form users will use to launch a job.
        required:
        - components
        items:
          type: object
          properties:
            attributes:
              description: |-
                A map of key/value pairs that optionally configure the form group.
              type: object
              additionalProperties:
                type: string
            components:
              type: array
              minItems: 1
              items:
                type: object
                description: |-
                  arbitrary keys corresponding to JSX PatternFly Form (e.g. TextInput or Radio) controls that contain a map of zero or more
                  attributes for the control; e.g.
                    - component: Radio
                      attributes:
                        label: Option 1
                properties:
                  inputType:
                    type: string
                    enum:
                    - TextArea
                    - TextInput
                    - Radio
                    - Checkbox
                  attributes:
                    description: |-
                      attributes is a map of {key,value} pairs that optionally contain attributes and values for the component
                    type: object
                    additionalProperties:
                      type: string
                  booleans:
                    type: array
                    items:
                      type: string
                required:
                - inputType
            var:
              description: |-
                Variable that will be assigned from the values of components in the group. Can be overriden at
                the component level.
              type: string
              pattern: '^\w+$'
      title:
        type: string

  GIG_RUN_STATUS:
    type: object
    properties:
      creationTimestamp:
        type: string
      result:
        type: string
        enum:
        - Aborted
        - Success
        - Failure
        - Pending
        default: Pending
      runTime:
        type: integer
      startedBy:
        type: string

elCicdDefs-$<GIG_DEF>:
  TITLE_CASE_NAME: GigDefinition
  SHORT_NAMES:
  - gigdef
  - gigdefs
  SCOPE: Cluster
  SPEC_DEFINITION:
    description: $<TITLE_CASE_NAME>Spec defines a GigDefinition, and the optional and/or required inputvalues to launch it.
    type: object
    properties:
      name:
        type: string
      description:
        type: string
      form: $<FORM_SPEC>
      secrets:
        type: array
        items:
          type: object
          properties:
            envVar:
              type: string
            secretRef:
              type: object
              properties:
                name:
                  type: string
      stages:
        description: Units of work.  User input may potentially be required at the end of a stage.
        type: array
        items:
          type: object
          properties:
            command:
              type: string
              descriptions: |
                Express a custom command to run this stage's script. The command should have the form
                <command> <args...> %s <args...>. %s will be used by Teknetes Gigs to inject the filename
                where the script is stored.
            displayName:
              type: string
              description: Human readable title of stage
            description:
              type: string
              description: Description of stage
            name:
              type: string
              description: |
                Name of stage. Must start and end with an alphanumeric character, and '-' and '.' may be used.
                The name will reflect the name of the file used to store the script, so name appropiately;
                e.g. <some-name>.py if writing a Python script for the stage.
              pattern: '(?:^\w(?:[-\w.]{0,251}[\w])?)$'
            script:
              type: string
            secretVars:
              type: array
              items:
                type: string
            processor:
              type: string
              enum:
              - Custom
              - Go
              - Input
              - Jinja
              - Python
              - Shell
              default: Shell
          required:
          - name
          - script

elCicdDefs-$<GIG>:
  TITLE_CASE_NAME: Gig
  SPEC_DEFINITION:
    description: $<TITLE_CASE_NAME>Spec defines the relationship between a $<GIG_DEF> and specific CronJob (i.e. JobTemplate).
    type: object
    properties:
      cronJobRef:
        description: Reference to a CronJob in the same Namespace as the Gig.
        type: object
        properties:
          name:
            description: Name of a CronJob in the same Namespace as the Gig.
            type: string
        required:
        - name
      gigDefinitionRef:
        description: Reference to a GigDefinition.
        type: object
        properties:
          name:
            type: string
        required:
        - name
    required:
    - cronJobRef
    - gigDefinitionRef
  STATUS_DEFINITION:
    type: object
    properties:
      latestGigRun:
        type: object
        properties:
          creationTimestamp:
            type: string
          result:
            type: string
            enum:
            - Aborted
            - Success
            - Failure
            - Pending
            default: Pending
          runTime:
            type: integer
          startedBy:
            type: string

elCicdDefs-$<GIG_RUN>:
  TITLE_CASE_NAME: GigRun
  INPUT_VALUES:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  SPEC_DEFINITION:
    description: $<TITLE_CASE_NAME>Spec defines a specific Job run produced from the parent Gig's CronJob.
    type: object
    properties:
      gigRef:
        type: object
        properties:
          name:
            type: string
            x-kubernetes-validations:
            - rule: "!(self != oldSelf)"
              message: gigRef name and containerName are immutable
          containerName:
            type: string
            x-kubernetes-validations:
            - rule: "!(self != oldSelf)"
              message: gigRef name and containerName are immutable
        required:
        - name
      form: $<FORM_SPEC>
      runState:
        type: string
        enum:
        - WaitingForInput
        - InputReceived
        - Running
        - Completed
        default: Running
      startedBy:
        type: string
        x-kubernetes-validations:
        - rule: "size(oldSelf) > 0 && !(self != oldSelf)"
          message: startedBy is immutable
    required:
    - gigRef
    - runState
  STATUS_DEFINITION:
    type: object
    properties:
      result:
        type: string
        enum:
        - Aborted
        - Success
        - Failure
        - Pending
        default: Pending
      runTime:
        type: integer

elCicdTemplates:
- apiVersion: apiextensions.k8s.io/v1
  kind: CustomResourceDefinition
  objNames: $<GIG_TYPES>
  objName: $<>s.batch.teknetes.org
  template:
    spec:
      conversion:
        strategy: None
      # group name to use for REST API: /apis/<group>/<version>
      group: batch.teknetes.org
      # list of versions supported by this CustomResourceDefinition
      names:
        kind: $<TITLE_CASE_NAME>
        plural: $<BASE_OBJ_NAME>s
        singular: $<BASE_OBJ_NAME>
        shortNames: $<SHORT_NAMES>
      scope: $<SCOPE>
      preserveUnknownFields: false
      versions:
      - name: v1beta1
        served: true
        storage: true
        subresources:
          status: {}
        schema:
          openAPIV3Schema:
            description: |-
              A Gig represents an impromptu Job with arbitrary scripts, and implies user input is required, potentially in mutliple stages.
            type: object
            properties:
              apiVersion:
                description: |-
                  APIVersion defines the versioned schema of this representation of an object.
                  Servers should convert recognized schemas to the latest internal value, and
                  may reject unrecognized values.
                  More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
                type: string
              kind:
                description: |-
                  Kind is a string value representing the REST resource this object represents.
                  Servers may infer this from the endpoint the client submits requests to.
                  Cannot be updated.
                  In CamelCase.
                  More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
                type: string
              metadata:
                type: object
              spec: $<SPEC_DEFINITION>
              status: $<STATUS_DEFINITION>