apiVersion: batch.ahplos.org/v1beta1
kind: GigModule
metadata:
  name: default-runtimes
spec:
  mode: Library
  runtimeDefs:
  - type: Script
    runtimes:
    - name: Go
      script: |-
        __runGoStep
    - name: JavaScript
      script: |-
        __runJavaScriptStep
    - name: Python
      script: |-
        __runPythonStep
    - name: Shell
      script: |-
        __runShellStep
  - type: Template
    runtimes:
    - name: Helm
      script: |-
        __renderHelmTemplate
    - name: JavaScript
      script: |-
        __renderJavaScriptTemplate
    - name: Jinja
      script: |-
        __renderJinjaTemplate
    - name: Shell
      script: |-
        __renderShellTemplate
  - type: UserInput
    runtimes:
    - name: Helm
      script: |-
        __runUserInput
    - name: JavaScript
      script: |-
        __runUserInput
    - name: Jinja
      script: |-
        __runUserInput
  supportFiles:
  {{- range $helperFile, $_ :=  .Files.Glob  "runtime-support/**.*" }}
  - name: {{ base $helperFile }}
    content: |-
      {{- $.Files.Get $helperFile | nindent 6}}
  {{- end }}