apiVersion: v2
name: gigs-operator-rbac
description: A Helm chart for Kubernetes

type: application
version: 0.1.0

dependencies:
- name: elcicd-chart
  version: 0.1.0
  repository: oci://ghcr.io/elcicd
