elCicdDefs:
  PLUGIN_NAME: ahplos-gigs-console-plugin
  OPERATOR_NAME: ahplos-gigs-operator

  IMAGE_REGISTRY: dev-demo-image-registry.apps-crc.testing
  AHPLOS_GIGS_PLUGIN_IMAGE: $<IMAGE_REGISTRY>/$<PLUGIN_NAME>:latest
  AHPLOS_GIGS_OPERATOR_IMAGE: $<IMAGE_REGISTRY>/$<OPERATOR_NAME>:latest

  AHPLOS_GIGS_IMAGE_PULL_SECRET: gig-demo-registry-credentials

  PORT: 8443

  IMAGE_PULL_POLICY: Always

  NGINX_CONF_VOLUME: nginx-conf
  NGINX_CONF: nginx.conf

  PATCH_SA_NAME: ahplos-console-patcher

  CERT_NAME: $<HELM_RELEASE_NAME>-cert

  GIGS_ADMIN_ROLE: gigs-admin

  GIGS_OCP_CONSOLE_ROLE: $<OPERATOR_NAME>-openshift-console

  AHPLOS_GIGS_INTERPRETER_MAP: ahplos-gigs-interpreters

elCicdDefs-dev:
  IMAGE_PULL_POLICY: Always

elCicdTemplates:
- templateNames: [deployment, service, serviceAccount]
  objName: $<OPERATOR_NAME>
  port: $<PORT>
  image: $<AHPLOS_GIGS_OPERATOR_IMAGE>
  imagePullSecrets:
  - name: $<AHPLOS_GIGS_IMAGE_PULL_SECRET>
  imagePullPolicy: $<IMAGE_PULL_POLICY>
  serviceAccountName: $<OBJ_NAME>
  workDir: /ahplos-gigs-controller
  command:
  - bash
  - -c
  - |-
    set -ex
    python --version
    python ./utilities/console_patch.py $<PLUGIN_NAME>
    kopf run --all-namespaces --verbose $(ls *_controller.py)
  env:
  - name: AHPLOS_GIGS_OPERATOR_NAMESPACE
    value: $<HELM_RELEASE_NAMESPACE>
  - name: AHPLOS_GIGS_OPERATOR_NAME
    value: $<OPERATOR_NAME>
  - name: AHPLOS_GIGS_OPERATOR_PORT
    value: $<toString|PORT>
  - name: AHPLOS_GIGS_INTERPRETER_MAP
    value: $<AHPLOS_GIGS_INTERPRETER_MAP>
  volumeMounts:
    - name: $<CERT_NAME>
      readOnly: true
      mountPath: /var/cert
  volumes:
    - name: $<CERT_NAME>
      secret:
        secretName: $<CERT_NAME>
        defaultMode: 0420

- templateName: configMap
  elCicdDefs:
    PYTHON_JINJA_COMMAND: python ${GIG_RUNNER_HOME}/jinja_stage.py %s
  objName: $<AHPLOS_GIGS_INTERPRETER_MAP>
  data:
    Go: go run %s
    Input: $<PYTHON_JINJA_COMMAND>
    JinjaTemplate: $<PYTHON_JINJA_COMMAND>
    Python: python -m trace -t %s
    Shell: source %s

- templateNames: [deployment, service, serviceAccount]
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: $<CERT_NAME>
  objName: $<PLUGIN_NAME>
  replicas: 2
  port: $<PORT>
  image: $<AHPLOS_GIGS_PLUGIN_IMAGE>
  imagePullSecrets:
  - name: $<AHPLOS_GIGS_IMAGE_PULL_SECRET>
  imagePullPolicy: $<IMAGE_PULL_POLICY>
  serviceAccountName: $<OBJ_NAME>
  command:
  - bash
  - -c
  - |-
    if echo "$POD_IP" | grep -qE '^([0-9]{1,3}\.){3}[0-9]{1,3}$'; then
        LISTEN_ADDRESS_PORT_REPLACED_AT_RUNTIME="$<toString|PORT>"
    else
        LISTEN_ADDRESS_PORT_REPLACED_AT_RUNTIME="[::]:$<toString|PORT>"
    fi
    sed "s/LISTEN_ADDRESS_PORT_REPLACED_AT_RUNTIME/$LISTEN_ADDRESS_PORT_REPLACED_AT_RUNTIME/g" /etc/nginx/$<NGINX_CONF> > /tmp/$<NGINX_CONF>

    nginx -c /tmp/$<NGINX_CONF> -g 'daemon off;'
  env:
  - name: POD_IP
    valueFrom:
      fieldRef:
        fieldPath: status.podIP
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  volumeMounts:
    - name: $<CERT_NAME>
      readOnly: true
      mountPath: /var/cert
    - name: $<NGINX_CONF_VOLUME>
      readOnly: true
      mountPath: /etc/nginx/$<NGINX_CONF>
      subPath: $<NGINX_CONF>
  volumes:
    - name: $<CERT_NAME>
      secret:
        secretName: $<CERT_NAME>
        defaultMode: 0420
    - name: $<NGINX_CONF_VOLUME>
      configMap:
        name: $<NGINX_CONF>
        defaultMode: 0420
        items:
        - key: $<NGINX_CONF>
          path: $<NGINX_CONF>

- templateName: configMap
  objName: $<NGINX_CONF>
  data:
    $<NGINX_CONF>: |-
      error_log /dev/stdout info;
      events {}
      http {
        access_log         /dev/stdout;
        include            /etc/nginx/mime.types;
        default_type       application/octet-stream;
        keepalive_timeout  65;
        server {
          listen              LISTEN_ADDRESS_PORT_REPLACED_AT_RUNTIME ssl;
          ssl_certificate     /var/cert/tls.crt;
          ssl_certificate_key /var/cert/tls.key;
          root                /usr/share/nginx/html;
        }
      }

- templateName: clusterRoleBinding
  objName: $<GIGS_OCP_CONSOLE_ROLE>
  subjects:
  - kind: ServiceAccount
    name: $<OPERATOR_NAME>
    namespace: $<HELM_RELEASE_NAMESPACE>
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: $<OBJ_NAME>

- apiVersion: console.openshift.io/v1
  objName: $<PLUGIN_NAME>
  kind: ConsolePlugin
  template:
    spec:
      displayName: $<OBJ_NAME>
      i18n:
        loadType: Preload
      backend:
        type: Service
        service:
          name: $<OBJ_NAME>
          namespace: $<HELM_RELEASE_NAMESPACE>
          port: $<PORT>
          basePath: /

- templateName: clusterRole
  objName: $<GIGS_OCP_CONSOLE_ROLE>
  rules:
  - apiGroups:
    - operator.openshift.io
    resources:
    - consoles
    verbs:
    - get
    - list
    - patch
    - update
  - apiGroups:
    - admissionregistration.k8s.io
    - batch
    resources:
    - validatingwebhookconfigurations
    - mutatingwebhookconfigurations
    - cronjobs/status
    - jobs/status
    verbs:
    - create
    - patch
  - verbs:
    - list
    - get
    - watch
    apiGroups:
    - apiextensions.k8s.io
    resources:
    - customresourcedefinitions

- templateName: clusterRole
  objName: $<GIGS_ADMIN_ROLE>
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: 'true'
  rules:
  - verbs:
    - '*'
    apiGroups:
    - ""
    resources:
    - pods
    - pods/status
    - pods/finalizers
    - secrets
    - secrets/finalizers
  - verbs:
    - '*'
    apiGroups:
    - batch
    resources:
    - jobs
    - jobs/status
    - jobs/finalizers
    - cronjobs
    - cronjobs/status
    - cronjobs/finalizers
  - verbs:
    - '*'
    apiGroups:
    - batch.ahplos.org
    resources:
    - gigmodules
    - gigforms
    - gigs
    - gigruns
    - gigmodules/status
    - gigforms/status
    - gigs/status
    - gigruns/status
    - gigmodules/finalizers
    - gigforms/finalizers
    - gigs/finalizers
    - gigruns/finalizers

- templateName: clusterRole
  objName: gigruns-runner
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: 'true'
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: 'true'
  rules:
  - apiGroups:
    - batch.ahplos.org
    resources:
    - gigruns
    verbs:
    - '*'
  - apiGroups:
    - batch.ahplos.org
    resources:
    - gigs
    - gigs/status
    - gigruns/status
    - gigforms
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    resources:
    - pods
    - pods/log
    - namespaces
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - project.openshift.io
    resources:
    - projects
    verbs:
    - get
    - list
    - watch

- templateName: clusterRoleBinding
  objName: $<OPERATOR_NAME>-namespace-admin
  subjects:
  - kind: ServiceAccount
    name: $<OPERATOR_NAME>
    namespace: $<HELM_RELEASE_NAMESPACE>
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: admin

- templateName: clusterRoleBinding
  objName: $<OPERATOR_NAME>-$<GIGS_ADMIN_ROLE>
  subjects:
  - kind: ServiceAccount
    name: $<OPERATOR_NAME>
    namespace: $<HELM_RELEASE_NAMESPACE>
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: $<GIGS_ADMIN_ROLE>
