elCicdDefs:
  TEKNETES_GIGS_IMAGE: dev-demo-image-registry.apps-crc.testing/test-console-plugin:latest
  TEKNETES_GIGS_IMAGE_PULL_SECRET: elcicd-dev-registry-credentials

  OPENSHIFT_PLUGIN_PORT: 9443
  IMAGE_PULL_POLICY: Always

  NGINX_CONF_VOLUME: nginx-conf
  NGINX_CONF: nginx.conf

  PATCH_SA_NAME: teknetes-console-patcher

  CERT_NAME: $<HELM_RELEASE_NAME>-cert

elCicdDefs-dev:
  IMAGE_PULL_POLICY: Always

elCicdTemplates:
- templateName: deployment
  replicas: 2
  port: $<OPENSHIFT_PLUGIN_PORT>
  image: $<TEKNETES_GIGS_IMAGE>
  imagePullSecrets:
  - name: $<TEKNETES_GIGS_IMAGE_PULL_SECRET>
  imagePullPolicy: $<IMAGE_PULL_POLICY>
  command:
  - bash
  - -c
  - |-
    if echo "$POD_IP" | grep -qE '^([0-9]{1,3}\.){3}[0-9]{1,3}$'; then
      LISTEN_ADDRESS_PORT_REPLACED_AT_RUNTIME="$<toString|OPENSHIFT_PLUGIN_PORT>"
    else
      LISTEN_ADDRESS_PORT_REPLACED_AT_RUNTIME="[::]:$<toString|OPENSHIFT_PLUGIN_PORT>"
    fi
    sed "s/LISTEN_ADDRESS_PORT_REPLACED_AT_RUNTIME/$LISTEN_ADDRESS_PORT_REPLACED_AT_RUNTIME/g" /etc/nginx/$<NGINX_CONF> > /tmp/$<NGINX_CONF>
    
    exec nginx -c /tmp/$<NGINX_CONF> -g 'daemon off;'
  env:
  - name: POD_IP
    valueFrom:
      fieldRef:
        fieldPath: status.podIP
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  volumeMounts:
    - name: $<CERT_NAME>
      readOnly: true
      mountPath: /var/cert
    - name: $<NGINX_CONF_VOLUME>
      readOnly: true
      mountPath: /etc/nginx/$<NGINX_CONF>
      subPath: $<NGINX_CONF>
  volumes:
    - name: $<CERT_NAME>
      secret:
        secretName: $<CERT_NAME>
        defaultMode: 0420
    - name: $<NGINX_CONF_VOLUME>
      configMap:
        name: $<NGINX_CONF>
        defaultMode: 0420
        items:
        - key: $<NGINX_CONF>
          path: $<NGINX_CONF>

- templateName: service
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: $<CERT_NAME>
  port: $<OPENSHIFT_PLUGIN_PORT>

- templateNames: [job, serviceAccount]
  objName: $<PATCH_SA_NAME>
  image: $<TEKNETES_GIGS_IMAGE>
  serviceAccountName: $<OBJ_NAME>
  imagePullSecrets:
  - name: $<TEKNETES_GIGS_IMAGE_PULL_SECRET>
  imagePullPolicy: $<IMAGE_PULL_POLICY>
  command:
  - bash
  - -c
  - |-
    EXISTING_PLUGINS=$(kubectl get consoles.operator.openshift.io cluster -o json | jq -c '.spec.plugins // []')
    MERGED_PLUGINS=$(jq --argjson existingPlugins "${EXISTING_PLUGINS}" --argjson consolePlugin \
        '["$<HELM_RELEASE_NAME>"]' -c  -n '$existingPlugins + $consolePlugin | unique')
    PATCHED_PLUGINS=$(jq --argjson mergedPlugins ${MERGED_PLUGINS} -n -c  '{ "spec": { "plugins": $mergedPlugins } }')
    kubectl patch consoles.operator.openshift.io cluster --patch ${PATCHED_PLUGINS} --type=merge

- templateName: configMap
  objName: $<NGINX_CONF>
  data:
    $<NGINX_CONF>: |-
      error_log /dev/stdout info;
      events {}
      http {
        access_log         /dev/stdout;
        include            /etc/nginx/mime.types;
        default_type       application/octet-stream;
        keepalive_timeout  65;
        server {
          listen              LISTEN_ADDRESS_PORT_REPLACED_AT_RUNTIME ssl;
          ssl_certificate     /var/cert/tls.crt;
          ssl_certificate_key /var/cert/tls.key;
          root                /usr/share/nginx/html;
        }
      }

- templateName: clusterRole
  objName: $<PATCH_SA_NAME>
  rules:
  - apiGroups:
    - operator.openshift.io
    resources:
    - consoles
    verbs:
    - get
    - list
    - patch
    - update

- templateName: clusterRoleBinding
  objName: $<PATCH_SA_NAME>
  subjects:
  - kind: ServiceAccount
    name: $<PATCH_SA_NAME>
    namespace: $<HELM_RELEASE_NAMESPACE>
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: $<PATCH_SA_NAME>

- apiVersion: console.openshift.io/v1
  kind: ConsolePlugin
  template:
    spec:
      displayName: $<OBJ_NAME>
      i18n:
        loadType: Preload
      backend:
        type: Service
        service:
          name: $<OBJ_NAME>
          namespace: $<HELM_RELEASE_NAMESPACE>
          port: $<OPENSHIFT_PLUGIN_PORT>
          basePath: $<OPENSHIFT_PLUGIN_BASEPATH>

- templateName: clusterRole
  objName: gigruns-admin
  rules:
  - verbs:
    - '*'
    apiGroups:
    - batch.teknetes.org
    resources:
    - clustergigdefinitions
    - gigdefinitions
    - gigs
    - gigruns

- templateName: clusterRole
  objName: gigruns-aggregate-to-edit
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: 'true'
    rbac.authorization.k8s.io/aggregate-to-edit: 'true'
  rules:
  - verbs:
    - create
    - delete
    - deletecollection
    - get
    - list
    - patch
    - update
    - watch
    apiGroups:
    - batch.teknetes.org
    resources:
    - gigdefinitions
    - gigs
    - gigruns
  - verbs:
    - get
    - list
    - watch
    apiGroups:
    - batch.teknetes.org
    resources:
    - clustergigdefinitions

- templateName: clusterRole
  objName: gigruns-aggregate-to-view
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: 'true'
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: 'true'
  rules:
  - verbs:
    - get
    - list
    - watch
    apiGroups:
    - batch.teknetes.org
    resources:
    - gigdefinitions
    - gigs
    - gigruns

- templateName: clusterRole
  objName: gigruns-runner
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: 'true'
  rules:
  - verbs:
    - create
    - delete
    - deletecollection
    - get
    - list
    - patch
    - update
    - watch
    apiGroups:
    - batch.teknetes.org
    resources:
    - gigruns
  - verbs:
    - get
    - list
    apiGroups:
    - batch.teknetes.org
    resources:
    - gigs


