elCicdDefs:
  GIG_MOD_DEMO: gig-mod-demo
  GIG_MOD_ASK_USER: gig-dif-ask-user
  GIG_MOD_SOURCE_DEMO: gig-mod-source-demo
  GIG_MOD_PRINT_MSG: gig-mod-print-msg-demo
  GIG_MOD_NAMES: [$<GIG_MOD_DEMO>, $<GIG_MOD_ASK_USER>, $<GIG_MOD_SOURCE_DEMO>, $<GIG_MOD_PRINT_MSG>]

  GIG_FORM_NAME: gig-form-demo

elCicdTemplates:
- apiVersion: batch.ahplos.org/v1beta1
  kind: GigForm
  objNames: [$<GIG_FORM_NAME>, $<GIG_FORM_NAME>]
  objName: $<GIG_FORM_NAME>-$<#>
  template:
    spec:
      formTitle:
        title:  Sign in as a cluster-admin for the Ahplos Gig Demonstration
      inputForm:
      - attributes:
          label: Cluster Admin User Name
          isRequired: true
          defaultValue: kubeadmin
          style:
            maxWidth: 50%
        inputType: Text
        var: CLUSTER_ADMIN_USER_NAME
      - attributes:
          label: Cluster Admin Password
          isRequired: true
          minLength: 6
          pattern: \w+
          type: password
          style:
            maxWidth: 50%
        helperText: |-
          Cluster admin passwords are at least 6 chars long
        inputType: Text
        var: CLUSTER_ADMIN_PASSWORD
      - attributes:
          isInline: true
          label: Visual Mode
          options:
          - Graphical
          - Logs
          defaultValue: Logs
        inputType: RadioGroup
        var: RUN_DEBUG_MODE

- apiVersion: batch.ahplos.org/v1beta1
  kind: GigModule
  objNames: $<GIG_MOD_NAMES>
  elCicdDefs:
    CHOOSE_DEMO_SOURCE_TYPES: choose-demo-source-types
    EXECUTE_DEMO_SOURCE_TYPES: execute-demo-source-types
    DEMONSTRATE_GO: demonstrate-go
    DEMONSTRATE_PYTHON: demonstrate-python
    PRINT_THE_DEMO_MSG: print-the-demo-msg

  elCicdDefs-$<GIG_MOD_DEMO>:
    GIG_MOD_SPECS:
      gigFormRef:
        name: $<GIG_FORM_NAME>-1
      requiredInputParams:
      - CLUSTER_ADMIN_USER_NAME
      - CLUSTER_ADMIN_PASSWORD
      secretVars:
      - CLUSTER_ADMIN_PASSWORD
      stages:
      - name: prove-parallel-stage
        description: Prove parallel processing works by making this step take longer than the rest of the Gig.
        maxParallel: 2
        steps:
        - name: sleep-in-the-background-in-first-stage
          sourceCode: |-
            sleep 40
        - name: print-message-from-first-stage
          sourceCode: |-
            echo 'PROVING PARALLEL PROCESSING BY STAGE WORKS BY PRINTING SECOOND STEP OF FIRST STAGE AT THE END'
      - name: login
        description: Login into cluster as cluster admin, and retrieve Gig supported Step interpreters.
        steps:
        - name: prove-parallel-step
          maxParallel: 2
          sourceCode: |-
            sleep 25
            echo 'PROVING PARALLEL PROCESSING BY STEP WORKS BY PRINTING SECOOND STEP OF FIRST STAGE AT THE END'
        - name: cluster-admin-login.sh
          sourceCode: |-
            SOME_VAR='Testing passing variables across stages and steps through the environment'
            echo "SOME_VAR: ${SOME_VAR}"
            echo "SOME_VAR='${SOME_VAR}'" >> .env
            oc login --insecure-skip-tls-verify -u ${CLUSTER_ADMIN_USER_NAME} -p ${CLUSTER_ADMIN_PASSWORD} https://kubernetes.default.svc
            sleep 2
      - name: $<CHOOSE_DEMO_SOURCE_TYPES>
        stageRef:
          gigModuleRef:
            name: $<GIG_MOD_ASK_USER>
      - name: $<DEMONSTRATE_GO>
        when: input.LANG_DEMO.includes('Go')
        stageRef:
          gigModuleRef:
            name: $<GIG_MOD_SOURCE_DEMO>
      - name: $<DEMONSTRATE_PYTHON>
        when: input.LANG_DEMO.includes("Python")
        maxParallel: 2
        iterate:
          when: env.INDEX != 2
          loops:
          - name: INDEX
            range:
              last: 3
          - name: VALS
            vector:
            - foo
            - 6
            - bar
            - baz
            - howdy
        stageRef:
          gigModuleRef:
            name: $<GIG_MOD_SOURCE_DEMO>

  elCicdDefs-$<GIG_MOD_ASK_USER>:
    GIG_MOD_SPECS:
      mode: Library
      stages:
      - name: $<CHOOSE_DEMO_SOURCE_TYPES>
        description: Have user choose which Gig supported interpreters to demo.
        steps:
        - name: retrieve-gig-operator-supported-languages
          sourceCode: |-
            echo "SOME_VAR: ${SOME_VAR}"
            JSON=$(oc get configmap ahplos-gigs-interpreters -n gigs-operator -o jsonpath='{.data}')
            LANGS=$(echo "${JSON}" | jq -r 'keys[]' | paste -sd ',' - | sed -E -e 's/([A-Z][A-Za-z.-]+)/"\1"\ /g')
            echo "{%- set LANGS = [${LANGS}] %}" > gig_interpreters.j2
            sleep 2
        - name: ask-user-what-languages-to-demo.j2
          interpreter: Input
          sourceCode: |-
            formTitle:
              title: 'Gig Interpreter(s) to demo'
            inputForm:
              {%- include 'gig_interpreters.j2' %}
              {%- from 'gig_interpreters.j2' import LANGS %}
              - attributes:
                  options: {{ LANGS }}
                inputType: CheckboxGroup
                var: LANG_DEMO

  elCicdDefs-$<GIG_MOD_SOURCE_DEMO>:
    GIG_MOD_SPECS:
      mode: Library
      stages:
      - name: $<DEMONSTRATE_GO>
        description: Set a test msg with a Go sourceCode and print it.
        steps:
        - name: set-test-msg-with.go
          interpreter: Go
          sourceCode: |-
            package main

            import (
                "os"
            )

            func main() {
                var f, _ = os.OpenFile(".env", os.O_CREATE|os.O_APPEND|os.O_WRONLY, 0755)
                defer f.Close()
                f.WriteString("\nTEST_MSG='This test msg was set using Go'")
            }
        - name: print-the-go-msg
          maxParallel: 2
          iterate:
            when: env.INDEX != 2
            loops:
            - name: INDEX
              range:
                last: 3
            - name: VALS
              vector:
              - foo
              - 6
              - bar
              - baz
              - howdy
          stepRef:
            gigModuleRef:
              name: $<GIG_MOD_PRINT_MSG>
            stage: $<PRINT_THE_DEMO_MSG>
            name: $<PRINT_THE_DEMO_MSG>
      - name: $<DEMONSTRATE_PYTHON>
        description: Set a test msg with a Python sourceCode and print it.
        steps:
        - name: set-test-msg-with.py
          interpreter: Python
          sourceCode: |-
            with open('.env', 'a') as env_file:
              env_file.write("\nTEST_MSG='This test msg was set using Python'")
        - name: print-the-python-msg
          stepRef:
            gigModuleRef:
              name: $<GIG_MOD_PRINT_MSG>
            stage: $<PRINT_THE_DEMO_MSG>
            name: $<PRINT_THE_DEMO_MSG>

  elCicdDefs-$<GIG_MOD_PRINT_MSG>:
    GIG_MOD_SPECS:
      mode: Library
      stages:
      - name: $<PRINT_THE_DEMO_MSG>
        description: Print the message assigned to the TEST_MSG environment variable.
        mode: Library
        steps:
        - name: $<PRINT_THE_DEMO_MSG>
          sourceCode: |-
            echo ${TEST_MSG}
            sleep 1
  template:
    spec: $<GIG_MOD_SPECS>