elCicdDefs:
  GIG_MOD_DEMO: gig-mod-demo
  GIG_MOD_GO_DEMO: gig-mod-go-demo
  GIG_MOD_JS_DEMO: gig-mod-javascript-demo
  GIG_MOD_PYTHON_DEMO: gig-mod-python-demo
  GIG_FORM_NAME: gig-mod-demo-form
  GIG_ORG_NAMEPACE: gig-demo-org

  GIGS_OPERATOR: gigs-operator

  GIGS_IMAGE_PULL_SECRET: gig-registry-credentials

  IMAGE: dev-demo-image-registry.apps-crc.testing/gigs-test-runner:latest

  SCHEDULE: '* * 30 2 *'

  OBJ_NAME_PREFIX: gig-demo

  SERVICE_ACCOUNT_NAME: $<OBJ_NAME_PREFIX>-sa

  SECRET_NAME: $<OBJ_NAME_PREFIX>-secrets

  GITHUB_HOOK: github-hook

  HISTORY_LIMIT: 15

elCicdTemplates:
- templateName: cronjob
  elCicdDefs:
    ANNOTATIONS:
      batch.ahplos.org/gigmodule: $<GIG_ORG_NAMEPACE>/$<OBJ_NAME>
  elCicdDefs-$<GIG_MOD_DEMO>:
    ANNOTATIONS:
      batch.ahplos.org/gigmodule: $<GIG_ORG_NAMEPACE>/$<OBJ_NAME>
      batch.ahplos.org/gigform: $<GIG_ORG_NAMEPACE>/$<GIG_FORM_NAME>
    ENV_FROM:
    - secretRef:
        name: $<SECRET_NAME>
  objNames: [$<GIG_MOD_DEMO>, $<GIG_MOD_GO_DEMO>, $<GIG_MOD_JS_DEMO>, $<GIG_MOD_PYTHON_DEMO>]
  annotations: $<ANNOTATIONS>
  failedJobsHistoryLimit: $<HISTORY_LIMIT>
  successfulJobsHistoryLimit: $<HISTORY_LIMIT>
  image: $<IMAGE>
  imagePullSecrets:
  - name: $<GIGS_IMAGE_PULL_SECRET>
  imagePullPolicy: IfNotPresent
  serviceAccountName: $<SERVICE_ACCOUNT_NAME>
  schedule: $<SCHEDULE>
  envFrom: $<ENV_FROM>

- templateNames: [serviceAccount, roleBinding]
  objName: $<SERVICE_ACCOUNT_NAME>
  subjects:
  - kind: ServiceAccount
    name: $<OBJ_NAME>
    namespace: $<HELM_RELEASE_NAMESPACE>
  roleRef:
    kind: ClusterRole
    name: edit

- templateName: roleBinding
  objName: developer-gigruns-runner
  subjects:
  - kind: User
    name: developer
  roleRef:
    kind: ClusterRole
    name: gigruns-runner

- templateName: roleBinding
  objName: developer-gigruns-runner
  namespace: $<GIG_ORG_NAMEPACE>
  subjects:
  - kind: User
    name: developer
  roleRef:
    kind: ClusterRole
    name: gigruns-runner

- templateName: secret
  objName: $<SECRET_NAME>
  stringData:
    A_SECRET: the demo secret

- templateName: secret
  objName: $<GITHUB_HOOK>
  stringData:
    secret: the demo secret

- apiVersion: batch.ahplos.org/v1beta1
  kind: GigHook
  objNames: [$<OBJ_NAME_PREFIX>, $<OBJ_NAME_PREFIX>]
  objName: $<OBJ_NAME_PREFIX>-$<#>
  template:
    spec:
      eventData:
      - key: X-GitHub-Event
        validation:
          match: ^push$
      - key: $.deleted
        source: Payload
        validation:
          bool: false
      - key: X-Hub-Signature-256
        validation:
          secretKeyRef:
            name: hook-secret
            key: hook-secret
          type: HMAC
      - key: $.ref
        source: Payload
        inputVar: SCM_BRANCH
        validation:
          match: ^refs/heads/development$

- templateName: secret
  objName: hook-secret
  stringData:
    hook-secret: my-test-secret

