elCicdTemplates-secrets:
- template:
    apiVersion: v1
    kind: Secret
    metadata:
      name: gig-demo-registry-credentials
    data:
      .dockerconfigjson: eyJhdXRocyI6eyJkZXYtZGVtby1pbWFnZS1yZWdpc3RyeS5hcHBzLWNyYy50ZXN0aW5nIjp7InVzZXJuYW1lIjoiZWxjaWNkZGV2IiwicGFzc3dvcmQiOiJhZG1pbjEyMyIsImF1dGgiOiJaV3hqYVdOa1pHVjJPbUZrYldsdU1USXoifX19
    type: kubernetes.io/dockerconfigjson