elCicdDefs:
  GIG_DEF_NAME: gig-def-demo
  GIG_FORM_NAME: gig-demo-launchform-2
  GIG_ORG_NAMEPACE: gig-demo-org

  ahplos_GIGS_OPERATOR: ahplos-gigs-operator

  ahplos_GIGS_IMAGE_PULL_SECRET: gig-demo-registry-credentials

  IMAGE: dev-demo-image-registry.apps-crc.testing/ahplos-gigs-test-runner:latest

  SCHEDULE: '* * 30 2 *'

  OBJ_NAME_PREFIX: gig-demo

  SERVICE_ACCOUNT_NAME: $<OBJ_NAME_PREFIX>-sa

  SECRET_NAME: $<OBJ_NAME_PREFIX>-secrets

  HISTORY_LIMIT: 15

elCicdTemplates:
- templateName: cronjob
  objNames: [$<OBJ_NAME_PREFIX>, $<OBJ_NAME_PREFIX>]
  objName: $<OBJ_NAME_PREFIX>-$<#>
  annotations:
    batch.ahplos.org/gigdefinition: $<GIG_ORG_NAMEPACE>/$<GIG_DEF_NAME>
    batch.ahplos.org/giglaunchform: $<GIG_ORG_NAMEPACE>/$<GIG_FORM_NAME>
  failedJobsHistoryLimit: $<HISTORY_LIMIT>
  successfulJobsHistoryLimit: $<HISTORY_LIMIT>
  image: $<IMAGE>
  imagePullSecrets:
  - name: $<ahplos_GIGS_IMAGE_PULL_SECRET>
  imagePullPolicy: IfNotPresent
  serviceAccountName: $<SERVICE_ACCOUNT_NAME>
  schedule: $<SCHEDULE>
  envFrom:
  - secretRef:
      name: $<SECRET_NAME>

- templateNames: [serviceAccount, roleBinding]
  objName: $<SERVICE_ACCOUNT_NAME>
  subjects:
  - kind: ServiceAccount
    name: $<OBJ_NAME>
    namespace: $<HELM_RELEASE_NAMESPACE>
  roleRef:
    kind: ClusterRole
    name: edit

- templateName: roleBinding
  objName: developer-gigruns-runner
  subjects:
  - kind: User
    name: developer
  roleRef:
    kind: ClusterRole
    name: gigruns-runner

- templateName: roleBinding
  objName: developer-gigruns-runner
  namespace: $<GIG_ORG_NAMEPACE>
  subjects:
  - kind: User
    name: developer
  roleRef:
    kind: ClusterRole
    name: gigruns-runner

- templateName: secret
  objName: $<SECRET_NAME>
  stringData:
    A_SECRET: the demo secret
