elCicdDefs:
  GIG_MOD_DEMO: gig-mod-demo
  GIG_MOD_ASK_USER: gig-dif-ask-user
  GIG_MOD_GO_DEMO: gig-mod-go-demo
  GIG_MOD_JS_DEMO: gig-mod-javascript-demo
  GIG_MOD_PYTHON_DEMO: gig-mod-python-demo
  GIG_MOD_PRINT_MSG: gig-mod-print-msg-demo
  GIG_MOD_NAMES: [$<GIG_MOD_DEMO>, $<GIG_MOD_ASK_USER>, $<GIG_MOD_GO_DEMO>, $<GIG_MOD_JS_DEMO>, $<GIG_MOD_PYTHON_DEMO>, $<GIG_MOD_PRINT_MSG>]

  GIG_FORM_NAME: gig-form-demo

elCicdTemplates:
- apiVersion: batch.ahplos.org/v1beta1
  kind: GigForm
  objNames: [$<GIG_FORM_NAME>, $<GIG_FORM_NAME>]
  objName: $<GIG_FORM_NAME>-$<#>
  template:
    spec:
      formTitle:
        title:  Sign in as a cluster-admin for the Ahplos Gig Demonstration
      inputForm:
      - attributes:
          label: Cluster Admin User Name
          isRequired: true
          defaultValue: kubeadmin
          style:
            maxWidth: 50%
        inputType: Text
        var: CLUSTER_ADMIN_USER_NAME
      - attributes:
          label: Cluster Admin Password
          isRequired: true
          minLength: 6
          pattern: \w+
          type: password
          style:
            maxWidth: 50%
        helperText: |-
          Cluster admin passwords are at least 6 chars long
        inputType: Text
        var: CLUSTER_ADMIN_PASSWORD
      - attributes:
          isInline: true
          label: Run inline or in separate GigRuns?
          options:
          - Inline
          - Separate GigRuns
          defaultValue: Inline
        inputType: RadioGroup
        var: RUN_INLINE

- apiVersion: batch.ahplos.org/v1beta1
  kind: GigModule
  objNames: $<GIG_MOD_NAMES>
  elCicdDefs:
    CHOOSE_DEMO_SOURCE_TYPES: choose-demo-source-types
    EXECUTE_DEMO_SOURCE_TYPES: execute-demo-source-types
    DEMONSTRATE_GO: demonstrate-go
    DEMONSTRATE_JAVASCRIPT: demonstrate-javascript
    DEMONSTRATE_PYTHON: demonstrate-python
    PRINT_THE_DEMO_MSG: print-the-demo-msg

  elCicdDefs-$<GIG_MOD_DEMO>:
    GIG_MOD_SPECS:
      gigFormRef:
        name: $<GIG_FORM_NAME>-1
      requiredInputParams:
      - CLUSTER_ADMIN_USER_NAME
      - CLUSTER_ADMIN_PASSWORD
      secretVars:
      - CLUSTER_ADMIN_PASSWORD
      stages:
      - name: prove-parallel-stage
        description: Prove parallel processing works by making this step take longer than the rest of the Gig.
        maxParallel: 1
        steps:
        - name: sleep-in-the-background-in-first-stage
          script: |-
            sleep 25
        - name: print-message-from-first-stage
          stepRef:
            gigModuleRef:
              name: $<GIG_MOD_PRINT_MSG>
            stage: $<PRINT_THE_DEMO_MSG>
            name: $<PRINT_THE_DEMO_MSG>
          args:
          - 'PROVING PARALLEL PROCESSING BY STAGE WORKS BY PRINTING SECOND STEP OF FIRST STAGE AT THE END'
      - name: login
        description: Login into cluster as cluster admin, and retrieve Gig supported Step runtimes.
        steps:
        - name: prove-parallel-step
          maxParallel: 1
          script: |-
            sleep 25
            echo 'PROVING PARALLEL PROCESSING BY STEP WORKS BY PRINTING FIRST STEP OF SECOND STAGE AT THE END'
        - name: cluster-admin-login.sh
          script: |-
            SOME_VAR='Testing passing variables across stages and steps through the environment'
            gigEnvSet SOME_VAR "${SOME_VAR}"
            echo "SOME_VAR: $(gigEnvGet SOME_VAR)"
            oc login --insecure-skip-tls-verify -u $(gigEnvGet CLUSTER_ADMIN_USER_NAME) \
                -p $(gigEnvGet CLUSTER_ADMIN_PASSWORD) https://kubernetes.default.svc
      - name: $<CHOOSE_DEMO_SOURCE_TYPES>
        stageRef:
          gigModuleRef:
            name: $<GIG_MOD_ASK_USER>
      - name: $<DEMONSTRATE_GO>
        when: gigEnv.LANG_DEMO.includes('Go')
        stageRef:
          gigModuleRef:
            name: $<GIG_MOD_GO_DEMO>
      - name: $<DEMONSTRATE_PYTHON>
        when: gigEnv.LANG_DEMO.includes("Python")
        maxParallel: 2
        iterate:
          loops:
          - name: INDEX
            range:
              last: 2
            when: env.INDEX != 2
          - name: VALS
            vector:
            - foo
            - 6
            - bar
        stageRef:
          gigModuleRef:
            name: $<GIG_MOD_PYTHON_DEMO>
      - name: $<DEMONSTRATE_JAVASCRIPT>
        when: gigEnv.LANG_DEMO.includes("JavaScript")
        # maxParallel: 2
        # iterate:
        #   loops:
        #   - name: LANG
        #     envVar:
        #       name: LANGS
        #     when: env.LANG == 'JavaScript'
        stageRef:
          gigModuleRef:
            name: $<GIG_MOD_JS_DEMO>

  elCicdDefs-$<GIG_MOD_ASK_USER>:
    GIG_MOD_SPECS:
      mode: Library
      stages:
      - name: $<CHOOSE_DEMO_SOURCE_TYPES>
        description: Have user choose which Gig supported runtimes to demo.
        steps:
        - name: retrieve-gig-operator-supported-languages
          script: |-
            echo "SOME_VAR [set in completely different module, stage, & step]: $(gigEnvGet SOME_VAR)"
            JSONPATH='.spec.versions[0].schema.openAPIV3Schema.properties.spec.properties.stages.items.properties.steps.items.properties.runtime.enum'
            LANGS_JSON="$(oc get crd gigmodules.batch.ahplos.org -o jsonpath="{${JSONPATH}}")"
            gigEnvSet LANGS_JSON ${LANGS_JSON}
            gigEnvSet LANGS $(echo $LANGS_JSON | jq -r '.[]'  | tr "\n" " ")
        - name: gigrun-operator-supported-languages-patch.yaml
          runtime: UserInput
          templateType: Helm
          script: |-
            formTitle:
              title: 'Gig Runtime(s) to demo'
            inputForm:
            - attributes:
                options: {{ .Values.gigEnv.LANGS_JSON | toYaml | nindent 4 }}
              inputType: CheckboxGroup
              var: LANG_DEMO

  elCicdDefs-$<GIG_MOD_GO_DEMO>:
    GIG_MOD_SPECS:
      requiredInputParams:
      - TEST_MESSAGE
      stages:
      - name: $<DEMONSTRATE_GO>
        description: Set a test msg with a Go script and print it.
        steps:
        - name: set-test-msg-with.go
          runtime: Go
          script: |-
            dir, _ := os.Getwd()
            fmt.Println("CURRENT DIR: " + dir)
            TEXT_MESSAGE := GigEnvGet("TEST_MESSAGE")
            GigEnvSet("TEXT_MESSAGE", ${TEST_MESSAGE})
        - name: print-the-go-msg
          maxParallel: 2
          iterate:
            loops:
            - name: INDEX
              range:
                last: 2
              when: env.INDEX != 1
            - name: VALS
              vector:
              - foo
              - 6
              - bar
          stepRef:
            gigModuleRef:
              name: $<GIG_MOD_PRINT_MSG>
            stage: $<PRINT_THE_DEMO_MSG>
            name: $<PRINT_THE_DEMO_MSG>

  elCicdDefs-$<GIG_MOD_JS_DEMO>:
    GIG_MOD_SPECS:
      stages:
      - name: $<DEMONSTRATE_JAVASCRIPT>
        description: Set a test msg with JavaScript script and print it.
        steps:
        - name: set-test-msg-with.js
          runtime: JavaScript
          script: |-
            let TEXT_MESSAGE = await gigEnvGet("TEXT_MESSAGE")
            TEXT_MESSAGE = TEXT_MESSAGE ? TEXT_MESSAGE + '\n' : ''
            await gigEnvSet("TEXT_MESSAGE", TEXT_MESSAGE + "This line of the test message was set using the Javascript runtime")
        - name: print-the-javascript-msg
          stepRef:
            gigModuleRef:
              name: $<GIG_MOD_PRINT_MSG>
            stage: $<PRINT_THE_DEMO_MSG>
            name: $<PRINT_THE_DEMO_MSG>

  elCicdDefs-$<GIG_MOD_PYTHON_DEMO>:
    GIG_MOD_SPECS:
      stages:
      - name: $<DEMONSTRATE_PYTHON>
        description: Set a test msg with Python script and print it.
        steps:
        - name: set-test-msg-with.py
          runtime: Python
          script: |-
            TEXT_MESSAGE = gigEnvGet("TEXT_MESSAGE")
            TEXT_MESSAGE = TEXT_MESSAGE + '\n' if TEXT_MESSAGE else ''
            gigEnvSet("TEXT_MESSAGE", TEXT_MESSAGE + "This line of the test message was set using the Python runtime")
        - name: print-the-python-msg
          stepRef:
            gigModuleRef:
              name: $<GIG_MOD_PRINT_MSG>
            stage: $<PRINT_THE_DEMO_MSG>
            name: $<PRINT_THE_DEMO_MSG>

  elCicdDefs-$<GIG_MOD_PRINT_MSG>:
    GIG_MOD_SPECS:
      mode: Library
      stages:
      - name: $<PRINT_THE_DEMO_MSG>
        description: Print the message assigned to the TEXT_MESSAGE environment variable.
        mode: Library
        steps:
        - name: $<PRINT_THE_DEMO_MSG>
          script: |-
            { set +x; } 2>/dev/null
            TEXT_MSG=${1:-$(stageEnvGet TEXT_MESSAGE)}
            echo "${TEXT_MSG:-$(gigEnvGet TEXT_MESSAGE)}"
            sleep 1
  template:
    spec: $<GIG_MOD_SPECS>